### ISSUE TITLE
problem downloading the dataset

### ISSUE THREAD

**Issue by YoelShoshan** [artcg/BEGAN#10]
Hello,

UPDATE: trying using the "baidu drive" option.
UPDATE2: downloading big files from baidu drive seems to require installing their executable which is not an option for me. Any idea, anyone?
not a problem with the code, just a problem downloading the celebs dataset.
http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
Dropbox doesn't like all the traffic it generated, and blocked access to the zip files.

Anyone here knows of a way to still get the dataset? any mirror or copy of the file anywhere?

**Comment by artcg** [comment]
Use Google Drive if the project Dropbox is down -- https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

I will add this info to the README as a couple of other people also had this problem

**Comment by YoelShoshan** [comment]
Thanks a lot! :)
