### ISSUE TITLE
datasets/celeba.h5

### ISSUE THREAD

**Issue by YiZiChen** [artcg/BEGAN#11]
Hi, thank you for you sharing.
But I can't find the celeba.h5, and error message = 'no such file or directory', 'datasets/celeba.h5'.

**Comment by artcg** [comment]
You can follow the instructions of the project README to download and prepare celeba.h5

**Comment by greentec** [comment]
@YiZiChen or you can make empty file 'celeba.h5' and use your own image files to make h5 file.
