### ISSUE TITLE
How to set the N?N is a num (0,1,,,)?

### ISSUE THREAD

**Issue by agingdata** [artcg/BEGAN#17]
Thanks,author!
I am suffer from some issues when trained a model and want to generate some samples simply run;
when I execute "python main.py --start-epoch=N add-epochs=0 --train=False"this line,some error appear.
can you share execute comand line?
where N is the checkpoint ,I have a little confused what it is a num or produced model? i have produced the model eg.BEGAN_64_64_0005.tfmod.data-00000-of-00001.
can you give some guide?
thanks again!

**Comment by artcg** [comment]
This repository is aimed at people with a working knowledge of python and tensorflow, please learn those if you would like to use the code
