### ISSUE TITLE
Bug suspicion on the discriminator

### ISSUE THREAD

**Issue by edubois** [artcg/BEGAN#19]
Just reading the code and I think I found something strange:

discriminator.py +62:
I read:
`layer_3 = custom_conv2d(conv_2, 3 * num_filters, k_h=3, k_w=3, d_h=2, d_w=2, scope='el3')`

Shouldn't it be:
`layer_3 = custom_conv2d(conv_4, 3 * num_filters, k_h=3, k_w=3, d_h=2, d_w=2, scope='el3')`

**Comment by artcg** [comment]
Thanks definitely looks like a typo, will run some experiments and fix it later on

**Comment by edubois** [comment]
You might get even better results :D
But your results are already awesome.
