### ISSUE TITLE
different size images

### ISSUE THREAD

**Issue by donovanr** [artcg/BEGAN#7]
Unless I'm misunderstanding something, it looks like there's some 64 px settings hard-coded into the model, e.g `grep -n 64 *.py: 
```
config.py:2:checkpoint_prefix = 'BEGAN_64_64'
discriminator.py:23:        D_I: a batch of images [batch_size, 64 x 64 x 3]
discriminator.py:30:            batch_size * 64 * 64 * 3
discriminator.py:39:                   .reshape([-1, 64, 64, 3]))  # '-1' is batch size
discriminator.py:136:                          .apply(tf.image.resize_nearest_neighbor, [64, 64]))
generator.py:31:            batch_size * 64 * 64 * 3
generator.py:83:                   .apply(tf.image.resize_nearest_neighbor, [64, 64]))
main.py:90:                hidden_size=2048, dim=(64, 64, 3), gpu_id='/gpu:0',
main.py:171:                  ('Generated 64x64 samples.', 'Random training images.'),
main.py:273:            im_to_save = im[n].reshape([64, 64, 3])
```
I'd like to use 128x128 px images -- what do you think would be the best way to do that?  Could I just replace all the 64s with 128s?  Or would another layer be necessary?

**Comment by artcg** [comment]
You would need another up-sample and down-sample layer in the generator and discriminator for best results -- also it's worth noting that you would have to pre-process your training data to 128x128! Shouldn't be too difficult, I will look into adding this as a feature

**Comment by donovanr** [comment]
Sounds good, thanks!

**Comment by donovanr** [comment]
I've been looking at `discriminator.py` and trying to add in extra layers, but something that's throwing me off is that in the encoder the second argument of `conv2d` and the first argument of `custom_conv2d` seem to grow proportionally with the layer number, e.g. `2 * n` in layer 2, `3 * n` in layer 3, etc.

In the generator and the decoder this isn't the case.  Apologies for my unfamiliarity with tensorflow, but could you explain a little what's going on with that, and how I might modify things to add an extra layer a the beginning and end of the autoencoder while not breaking this pattern?

**Comment by artcg** [comment]
That argument is the number of filters for the Conv layer - in general you don't want it *too* low since then you will have a sort of bottleneck on what you can learn so that is why I scale it up to 4 * n (as the dimensionality of the image representation is getting lower, the number of filters is getting higher)

You might find it easiest to add the 128 layer by leaving that argument as it is for other layers and just copying the 64 layer argument for the 128 layer

**Comment by donovanr** [comment]
thanks, that makes sense.

**Comment by artcg** [comment]
Added support in https://github.com/artcg/BEGAN/commit/ff6b72bf7afc7b0ad1c5eddad63ebacf5558cc72
