### ISSUE TITLE
monitoring models during training

### ISSUE THREAD

**Issue by donovanr** [artcg/BEGAN#8]
I added a couple of line to monitor the convergence of the model during training:
```
logging_data = np.array([loss_tracker['generator'],loss_tracker['discriminator'],loss_tracker['convergence_measure']])
            logging_data = logging_data.T
            np.savetxt("convergence_measure.txt", logging_data, fmt='%.15e', header="            generator         discriminator   convergence_measure", comments='')
```
and I see what I'd more or less expect in the generator and discriminator columns, but the convergence_measure is always all zeros.

I see that you're appending zeros to the convergence_measure in the loss tracker in lines 158-160:
```
            loss_tracker['generator'].append(G_loss_)
            loss_tracker['discriminator'].append(D_loss_)
            loss_tracker['convergence_measure'].append(0)
```
Why is that? Is there a (better) way to access this info?

**Comment by artcg** [comment]
Nice! Looks like I forgot to actually add the convergence measure to the tracker and instead was adding zeroes for some reason... I *think* it should be fixed in https://github.com/artcg/BEGAN/commit/9cfa9980e7620897a398a58eb94e719ac0eb8eaa (can't test now since I am at work)

**Comment by donovanr** [comment]
Thanks, that seemed to work just fine.

What would you recommend as a good way to print out some sample images every epoch?  Some combination of what you have in the `if demo` block and the `if not args.train` block seems about like what i'm after, but I want to make sure i'm not stepping the models through data for the sake of printing pictures that it otherwise needs to train on.  I'm unfamiliar with TF that the `sess.run` makes me nervous about pasting things around...

**Comment by artcg** [comment]
Good to hear! I don't think you should worry too much about the computation of running an extra batch of images to save for performance checking -- would be negligible compared to training time
